setwd("~/R/projects/calicantus/run/cams")
source("~/R/projects/calicantus/R/cams.R")
nc <- get_cams(pollutant = c("PM10","O3","PM25"))
source("~/R/projects/calicantus/R/cams_daily_synthesis.R")
source("~/R/projects/calicantus/R/cams_timeseries.R")
archive_cams()
archive_cams_timeseries()
setwd("~/R/projects/calicantus/run/cams")
file.remove(nc)